### PR TITLE
[ISSUE-60] Drupal 10 compatibility

### LINKED ISSUE #60: Drupal 10 compatibility version
See more details in drupal.org issue:

https://www.drupal.org/project/quantcdn/issues/3289207

### PR DESCRIPTION
**Pull request by kepol**

### CODE REVIEW

**Comment by kepol** [comment]
I've tested on 9.4.5 but not on 10 yet.

**Comment by kepol** [comment]
Tested on Drupal 10 with seeding and search and it is working as expected.

**Comment by kepol** [comment]
For this one, we'll need to consider creating a new version, since we shouldn't be supporting Drupal 8 anymore.

CI is using Drupal 8... and this code is set up for `^9.3 || ^10`, so it doesn't pass.

Screen Shot 2022-09-02 at 2 16 22 PM

**Comment by kepol** [comment]
My attempt at hacking this didn't work :) so I'll need some guidance as to where the `container: quantcdn/drupal-ci:9.2.x-dev` stuff is set up.

**Comment by kepol** [comment]
Seems to be this but I'll hold off until we can talk it through: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

**Comment by barbun** [comment]
Re-roll against the latest 1.x:
https://github.com/quantcdn/drupal/pull/69

**Comment by kepol** [comment]
Fixed in https://github.com/quantcdn/drupal/pull/69

Thanks @barbun!

**Pull request closed without merging**
