### PR TITLE
Search autocomplete

### PR DESCRIPTION
**Pull request by stooit**
Screenshot 2022-11-30 at 8 39 27 AM

Adds new search autocomplete functionality. 

This allows for placement of configurable autocomplete blocks that:
* can inherit the filters of a parent search page (e.g limit by content type, language, apply any other filters)
* can optionally show search item summary along with title
* supports keyboard navigation
* will jump the user to the search page if enter is pressed and no search item result is selected
* easily styled via twig

### CODE REVIEW

**Comment by kepol** [comment]
I'm going to be adding my notes here so ignore for now:

1. Worried about possible naming confusion since `autocomplete_block` is very generic sounding
2. You can place a block without having a search page and it causes fatal error when viewing site
3. Seems to be working well from what I can tell other than above

Note: I tested with regular words and also with `!@#$%^&*()_+:"?><;'/.,`~=+-_` which ended up doing a search of `!@`. Not sure if all special characters should be removed?

I still need to review the code more carefully.

**Comment by kepol** [comment]
I added a bit of error handling.

We still need to handle the case when someone tries to add more than one block because the second block doesn't render (it does show the title). I assume this is due to Algolia getting confused or intentionally not allowing multiples.

I guess we should just not allow adding a second block. Not sure the cleanest place to do that.

**Comment by kepol** [comment]
I'm done reviewing for now... outstanding items:

1. Worried about possible naming confusion since `autocomplete_block` is very generic sounding... could be more explicit like `quant_search_block`
2. Should we strip all special characters (see example above)
3. Figure out best place to restrict block placement so you can only place one search block

**Comment by kepol** [comment]
Ignore 3 in last comment... we don't want to restrict this because they might have a different search block on a different page using visibility settings. We should just put in the documentation that you can only have one search block per page.

**Comment by stooit** [comment]
Sounds good, I think:

1. Yeah, can rename to `quant_autocomplete_block`? Only needs to change in a couple of places
2. This is the standard practice recommended by the Algolia library, so yes I think this should stay as is
3. I think we can probably just explain this in docs: You can have multiple blocks but it is not expected you display multiple on the same page

**Comment by kepol** [comment]
1. `quant_autocomplete_block`  sounds fine... then at least it's clear where it's from
2. Gotcha
3. Agreed

**Comment by stooit** [comment]
@kepol renamed the block plugin id to `quant_autocomplete_block`

**Comment by kepol** [comment]
Thanks... tested and it's looking pretty good... wondering about the special characters here though

Screen Shot 2022-11-29 at 10 58 14 PM

These look fine:

Screen Shot 2022-11-29 at 10 58 41 PM

Screen Shot 2022-11-29 at 10 59 04 PM

**Comment by stooit** [comment]
> Thanks... tested and it's looking pretty good... wondering about the special characters here though

Ah, yes. This is an existing issue that this PR will actually fix (https://github.com/quantcdn/drupal/pull/73/files#diff-fb5b669201fcfe07cbaf08ebfed21e8dc7f4820b290ea10b714f17e1300660cbR234)

If you reindex your content then those decoded characters will disappear ✨

**Comment by kepol** [comment]
Strange... I've cleared caches, reseeded, reindexed, resaved, delete block and readded, but I'm still seeing the decoded characters... maybe I just need to sleep on it and it will fix itself

**Comment by stooit** [comment]
Ah, yeah - turns out `&#039;` and any `&#[0-9]+` are not actually decoded by `html_entity_decode` properly.

I'll write another sanitisation method to get these to utf-8 and update.

**Comment by stooit** [comment]
Should be sorted now after a reindex @kepol 

Screenshot 2022-12-01 at 9 04 17 AM

**Comment by kepol** [comment]
Great! I'll be able to test it after class tonight :)

**Comment by kepol** [comment]
Actually... I was able to just test it...

Screen Shot 2022-11-30 at 12 32 14 PM

I'll merge!

**Pull request merged**
