### PR TITLE
[ISSUE-58] Add tabledrag table to search facet configuration.

### LINKED ISSUE #58: Allow reordering of search facets
See details in drupal.org issue:

https://www.drupal.org/project/quantcdn/issues/3307338

### PR DESCRIPTION
**Pull request by kepol**
Allow drag-and-drop to reorder facets and clean up the styling so it's easier to work with facets.

### CODE REVIEW

**Comment by kepol** [comment]
Needs theming tweaks and more testing but here are some screenshots:

Screen Shot 2022-09-01 at 11 18 59 AM

Screen Shot 2022-09-01 at 11 19 09 AM

Screen Shot 2022-09-01 at 11 19 31 AM

Screen Shot 2022-09-01 at 11 19 47 AM

Screen Shot 2022-09-01 at 11 20 14 AM

**Comment by kepol** [comment]
Basic styling for desktop and smaller screens. The first select styling is being annoying, I think because of the tabledrag tacked onto it but I'm not going to spend more time on it for now.

Screen Shot 2022-09-01 at 3 09 54 PM

Screen Shot 2022-09-01 at 3 10 14 PM

Screen Shot 2022-09-01 at 3 12 26 PM


Screen Shot 2022-09-01 at 3 12 03 PM

**Comment by kepol** [comment]
The reordered facets show up on the quant preview site as expected.

Screen Shot 2022-09-01 at 3 43 18 PM

Screen Shot 2022-09-01 at 3 42 57 PM

Screen Shot 2022-09-01 at 3 43 40 PM

**Comment by kepol** [comment]
There will be some merge conflicts so maybe review this last and I'll fix those before you review.

**Comment by kepol** [comment]
Merged all the other changes in here and fixed a bug I found when testing and now everything seems to be working okay.

WIth facets:

https://a8df6363-f067-4026-9eac-01497561c3e4.sites.quantcdn.io/whatsup/changed

Without facets:

https://a8df6363-f067-4026-9eac-01497561c3e4.sites.quantcdn.io/ugh

The form styling is shown in screenshots above.

**Comment by kepol** [comment]
Recording: https://drive.google.com/file/d/1srcbCIcyfjj6SCm_GBTvhhOrD1Lv3iIT/view?usp=sharing

**Review by stooit — APPROVED** [review]
Tested upgrade pathway & fresh install, major UX improvement!

**Pull request merged**
