### PR TITLE
Added support for "Disable content drafts" for terms.

### PR DESCRIPTION
**Pull request by kepol**
Drupal.org issue: https://www.drupal.org/project/quantcdn/issues/3342521

### CODE REVIEW

**Comment by kepol** [comment]
I've tested as follows:

1. With "Track content change" and "Disable content drafts" enabled

- Create unpublished term => (worked) doesn't show in quant
- Publish the term => (worked) shows in quant as published
- Unpublish the term => (worked) shows in quant as unpublished
- Run seed/run queue => (worked) still shows in quant as unpublished

2. With "Track content change" enabled and "Disable content drafts" disabled

- **Create unpublished term => (didn't worked) should show in quant as unpublished but didn't show up**
  - **Different bug... doesn't work without PR either...**
- Publish the term => (worked) shows in quant as published
- Unpublish the term => (worked) shows in quant as unpublished
- Run seed/run queue => (worked) still shows in quant as unpublished

3. With "Track content change" disabled and "Disable content drafts" enabled

- Create unpublished term => (worked) doesn't show in quant
- Run seed/run queue => (worked) doesn't show in quant
- Publish the term => (worked) doesn't show in quant
- Run seed/run queue => (worked) shows in quant as published
- Unpublish the term => (worked) doesn't show in quant as unpublished
- **Run seed/run queue => (didn't work) should show in quant as unpublished but still shows as published**
  - **Must be related to the bug above**

4. With "Track content change" disabled and "Disable content drafts" disabled

- Create unpublished term => (worked) doesn't show in quant
- Run seed/run queue => (worked) shows in quant as unpublished
- Publish the term => (worked) doesn't show in quant as published
- Run seed/run queue => (worked) shows in quant as published
- Unpublish the term => (worked) doesn't show in quant as unpublished
- **Run seed/run queue => (didn't work) should show in quant as unpublished but still shows as published**
  - **Must be related to the bug above**

The bug above must be because the code isn't processing unpublished terms.

**Comment by kepol** [comment]
Moving this one forward despite the additional bug noted in the previous comment. That can be fixed separately as it's unrelated to getting the "Disable content drafts" working for taxonomy terms.

**Comment by kepol** [comment]
I see I had already created an issue for it: https://www.drupal.org/project/quantcdn/issues/3344492

**Review by steveworley — APPROVED** [review]

**Comment by steveworley** [comment]
Looks good @kepol can you fix the conflict and merge away!

**Comment by kepol** [comment]
Thanks! Will do :)

**Pull request merged**
