### PR TITLE
Drupal 10 compatibility

### PR DESCRIPTION
**Pull request by barbun**
Re-roll of #61 against the latest 1.x

### CODE REVIEW

**Review by steveworley — APPROVED** [review]
Awesome! Code looks good, I'll get in and do some testing soon! Thanks @barbun

**Comment by kepol** [comment]
Ran into error noted here:

https://www.drupal.org/project/quantcdn/issues/3289207#comment-14806584

**Comment by kepol** [comment]
Hold up... this was probably because I didn't do the lenient endpoint.

**Comment by kepol** [comment]
Yeah, DrupalPod was being weird (it was already in the lenient endpoint list) but I added again in composer and was able to install on `10.0.0-rc1`. Things appear to be working as expected.

https://76d71747-59df-4d5a-9a35-b8829972f52e.sites.quantcdn.io/recipes/search

Note that we have quite a few changes coming very soon so I'm inclined to merge this in while it's working or it may need another reroll.

**Comment by kepol** [comment]
Thanks @barbun! We are hoping to get a `1.4.0` release out soon... hopefully this week.

**Pull request merged**
