### PR TITLE
Hardcode the CI mariadb version to get around failure.

### PR DESCRIPTION
**Pull request by kepol**
See d.o issue: https://www.drupal.org/project/quantcdn/issues/3366600

### CODE REVIEW

**Review by steveworley — APPROVED** [review]

**Comment by steveworley** [comment]
Awesome!

**Comment by OrbisK** [comment]
FYI: might be related to this:

> 11.0, unlike previous version, no longer includes mysql named compatible executable symlinks inside the container.

https://mariadb.com/kb/en/mariadb-11-0-1-release-notes/#docker-official-images

(got the same issue)


EDIT:
The healthcheck is the problem. Due to the mysql symlinks.
This should work with MariaDB:11
```
services:
  mariadb:
     environment:
       MARIADB_MYSQL_LOCALHOST_USER: true
     healthcheck:
       test: ["CMD", "/usr/local/bin/healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
```

**Comment by kepol** [comment]
Sweet! Thanks so much @OrbisK. I'll open a new ticket for this :)

**Comment by kepol** [comment]
Creating the issue here for now but will point to this once there is a new PR: https://www.drupal.org/project/quantcdn/issues/3370363

**Comment by kepol** [comment]
Released: https://github.com/quantcdn/drupal/releases/tag/1.5.2

**Pull request merged**
